# **CNN 2D**

### **【問題1】【問題2】**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
x = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]])

x_hat = np.zeros((2, 2, 3, 3))
for oh in range(2):
    for ow in range(2):
        x_hat[oh, ow, :, :] = x[oh:oh+3, ow:ow+3]
x_hat

array([[[[ 1.,  2.,  3.],
         [ 5.,  6.,  7.],
         [ 9., 10., 11.]],

        [[ 2.,  3.,  4.],
         [ 6.,  7.,  8.],
         [10., 11., 12.]]],


       [[[ 5.,  6.,  7.],
         [ 9., 10., 11.],
         [13., 14., 15.]],

        [[ 6.,  7.,  8.],
         [10., 11., 12.],
         [14., 15., 16.]]]])

In [3]:
x_hat = np.zeros((3, 3, 2, 2))
for fh in range(3):
    for fw in range(3):
        x_hat[fh, fw, :, :] = x[fh:fh+2, fw:fw+2]
x_hat

array([[[[ 1.,  2.],
         [ 5.,  6.]],

        [[ 2.,  3.],
         [ 6.,  7.]],

        [[ 3.,  4.],
         [ 7.,  8.]]],


       [[[ 5.,  6.],
         [ 9., 10.]],

        [[ 6.,  7.],
         [10., 11.]],

        [[ 7.,  8.],
         [11., 12.]]],


       [[[ 9., 10.],
         [13., 14.]],

        [[10., 11.],
         [14., 15.]],

        [[11., 12.],
         [15., 16.]]]])

In [4]:
x_tilde = x_hat.transpose((2, 3, 0, 1))
x_tilde

array([[[[ 1.,  2.,  3.],
         [ 5.,  6.,  7.],
         [ 9., 10., 11.]],

        [[ 2.,  3.,  4.],
         [ 6.,  7.,  8.],
         [10., 11., 12.]]],


       [[[ 5.,  6.,  7.],
         [ 9., 10., 11.],
         [13., 14., 15.]],

        [[ 6.,  7.,  8.],
         [10., 11., 12.],
         [14., 15., 16.]]]])

In [5]:
x_col = x_tilde.reshape(2, 2, -1)
x_col

array([[[ 1.,  2.,  3.,  5.,  6.,  7.,  9., 10., 11.],
        [ 2.,  3.,  4.,  6.,  7.,  8., 10., 11., 12.]],

       [[ 5.,  6.,  7.,  9., 10., 11., 13., 14., 15.],
        [ 6.,  7.,  8., 10., 11., 12., 14., 15., 16.]]])

In [6]:
f = np.array([[-1, 0, 1],
              [0, 2, 1],
              [1, -1, 0]])

np.dot(x_col, f.flatten())

array([[20., 23.],
       [32., 35.]])

**im2col関数**

In [7]:
def im2col(X, FH, FW):
    H, W = X.shape
    OH = H - FH + 1
    OW = W - FW + 1
    
    X_hat = np.zeros((FH, FW, OH, OW))
    for fh in range(FH):
        for fw in range(FW):
            X_hat[fh, fw, :, :] = X[fh:fh+OH, fw:fw+OW]
    X_tilde = X_hat.transpose(2, 3, 0, 1)
    X_col = X_tilde.reshape(OH, OW, -1)
    return X_col

In [8]:
X = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

F = np.array([[-1, 0, 1],
              [0, 2, 1],
              [1, -1, 0]])

X_col = im2col(X, 3, 3)
print(X_col)
print(np.dot(X_col, F.flatten()))

[[[ 1.  2.  3.  5.  6.  7.  9. 10. 11.]
  [ 2.  3.  4.  6.  7.  8. 10. 11. 12.]]

 [[ 5.  6.  7.  9. 10. 11. 13. 14. 15.]
  [ 6.  7.  8. 10. 11. 12. 14. 15. 16.]]]
[[20. 23.]
 [32. 35.]]


In [9]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [8, 9, 10]])
b = np.pad(a, [(1, 1), (1, 1)])
b

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  0],
       [ 0,  4,  5,  6,  0],
       [ 0,  8,  9, 10,  0],
       [ 0,  0,  0,  0,  0]])

In [10]:
a = np.arange(6)
a[0:6:2]

array([0, 2, 4])

**im2col関数（stride, padding対応版）**

In [11]:
def im2col(X, FH, FW, stride=1, pad=0):
    H, W = X.shape
    OH = (H + 2*pad - FH) // stride + 1 # 割り切れない場合は丸め込み
    OW = (W + 2*pad - FW) // stride + 1
    
    X_hat = np.zeros((FH, FW, OH, OW))
    for fh in range(FH):
        for fw in range(FW):
            X_hat[fh, fw, :, :] = X[fh:fh+OH*stride:stride, fw:fw+OW*stride:stride]
    X_tilde = X_hat.transpose(2, 3, 0, 1)
    X_col = X_tilde.reshape(OH, OW, -1)
    return X_col

In [12]:
X = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

F = np.array([[-1, 1],
              [2, 1]])

X_col = im2col(X, 2, 2, stride=2, pad=0)
np.dot(X_col, F.flatten())

array([[17., 23.],
       [41., 47.]])

**X.shapeが(Batch, Channel, H, W)のときのim2col関数**

In [13]:
# 入力データが4次元配列(mini_batch, channel, height, width)
def im2col(X, FH, FW, stride=1, pad=0):
    N, C, H, W = X.shape
    OH = (H + 2*pad - FH) // stride + 1
    OW = (W + 2*pad - FW) // stride + 1
    
    # (N, C, H, W)のうちHとW方向にのみpadding
    X_pad = np.pad(X, [(0, 0), (0, 0), (pad, pad), (pad, pad)])
    # さっきのものにN, Cをつける
    X_hat = np.zeros((N, C, FH, FW, OH, OW))
    for fh in range(FH):
        for fw in range(FW):
            X_hat[:, :, fh, fw, :, :] = X[:, :, fh:fh+OH*stride:stride, fw:fw+OW*stride:stride]
    # 引き伸ばしてベクトルの内積計算に持ち込む
    # 目標のshapeは(N, OH, OW, C*FH*FW)
    X_tilde = X_hat.transpose(0, 4, 5, 1, 2, 3) # X_tilde.shape: (N, OH, OW, C, FH, FW)
    X_col = X_tilde.reshape(N, OH, OW, -1)
    return X_col

In [14]:
K = 10
C = 3
H = 7
W = 7
FN = 4
FH = 3
FW = 3
# OH = 5
# OW = 5

X = np.random.rand(K, C, H, W)
F = np.random.rand(FN, C, FH, FW)

X_col = im2col(X, FH, FW, stride=1, pad=0)
f_col = F.reshape(FN, -1).T # F.shape: (FN, C, FH, FW)
# np.dot(X_col, f_col): (K, OH, OW, C*FH*FW)(FN, C*FH*FW) → (K, OH, OW, FN)
y = np.dot(X_col, f_col).transpose(0, 3, 1, 2) # (K, OH, OW, FN) → (K, FN, OH, OW)
y.shape

(10, 4, 5, 5)

**とりあえずforwardまでのConv2dを作成**

In [15]:
class Conv2d:
    def __init__(self, F, b, stride=1, pad=0):
        self.F = F
        self.b = b
        self.stride = stride
        self.pad = pad
        
    def forward(self, X):
        N, C, H, W = X.shape
        FN, C, FH, FW = self.F.shape
        self.stride = stride
        self.pad = pad
        
        # 出力サイズ
        OH = (H + 2*pad - FH) // stride + 1
        OW = (W + 2*pad - FW) // stride + 1
        
        # (N, C, H, W)のうちH, W方向にのみpadding
        X_pad = np.pad(X, [(0, 0), (0, 0), (pad, pad), (pad, pad)])
        
        # X_hat(空箱)を用意。型は(N, C, FH, FW, OH, OW)
        X_hat = np.zeros((N, C, FH, FW, OH, OW))
        
        for fh in range(FH):
            for fw in range(FW):
                X_hat[:, :, fh, fw, :, :] = X_pad[:, :, fh:fh+OH*stride:stride, fw:fw+OW*stirde:stride]
                
        # 引き伸ばしてベクトル内積計算に持ち込む
        # 目標のX_col.shape: (N, OH, OW, C*FH*FW)
        # まずは(N, OH, OW, C, FH, FW)にしたい
        # X_hat.shape: (N, C, FH, FW, OH, OW)
        X_tilde = X_hat.transpose(0, 4, 5, 1, 2, 3) # X_tilde.shape: (N, OH, OW, C, FH, FW)
        X_col = X_tilde.reshape(N, OH, OW, -1) # (N, OH, OW, C*FH*FW)
        
        # 出力yを計算
        F_col = self.F.reshape(FN, -1).T # F_col.shape: (FN, C*FH*FW) → (C*FH*FW, FN)
        # np.dot(X_col, F_col).shape: (N, OH, OW, FN)
        # y.shape: (N, FN, OH, OW)
        # transpose(0, 3, 1, 2)
        # b.shape: (FN,)
        y = (np.dot(X_col, F_col) + self.b).transpose(0, 3, 1, 2) # (N, FN, OH, OW)
        
        return y

**backwardを考える**

In [16]:
dy = np.array([[1, 2],
               [3, 4]])

F = np.array([[1, 1, 0],
              [1, 0, 1],
              [0, 1, 1]])

結局やりたいことは、ロスの出力による偏微分と入力のテンソル積

$$ \frac{\partial L}{\partial w_{st}} = \sum_{i}^{M-m} \sum_{j}^{N-n} \frac{\partial L}{\partial y_{ij}} x_{(i+s)(j+t)} $$

In [17]:
print(dy.reshape(2, 2, 1))
print(F.reshape(3, 1, 3))
dX_tilde = np.dot(dy.reshape(2, 2, 1), F.reshape(3, 1, 3))
print(dX_tilde.shape)

[[[1]
  [2]]

 [[3]
  [4]]]
[[[1 1 0]]

 [[1 0 1]]

 [[0 1 1]]]
(2, 2, 3, 3)


In [18]:
dX = np.zeros((4, 4))

for fh in range(3):
    for fw in range(3):
        dX[fh:fh+2, fw:fw+2] += dX_tilde[:, :, fh, fw]
        
print(dX)

[[1. 3. 2. 0.]
 [4. 9. 5. 2.]
 [3. 5. 6. 6.]
 [0. 3. 7. 4.]]


In [19]:
dy = np.array([[1, 2],
               [3, 4]])

X = np.array([[1, 1, 1, 1],
              [2, 2, 2, 2],
              [3, 3, 3, 3],
              [4, 4, 4, 4]])
X_hat = np.zeros((3, 3, 2, 2))
for fh in range(3):
    for fw in range(3):
        X_hat[fh, fw, :, :] = X[fh:fh+2, fw:fw+2]

print('X_hat.shape:', X_hat.shape)
Xh_col = X_hat.reshape(3, 3, -1)
print('Xh_col.shape:', Xh_col.shape)
dF = np.dot(Xh_col, dy.flatten())
db = dy.sum()
print('dF:', dF, 'db:', db)

X_hat.shape: (3, 3, 2, 2)
Xh_col.shape: (3, 3, 4)
dF: [[17. 17. 17.]
 [27. 27. 27.]
 [37. 37. 37.]] db: 10


**backwardも含めた完成版**

In [20]:
class Conv2d:
    def __init__(self, F, b, stride=1, pad=0):
        self.F = F
        self.b = b
        self.stride = stride
        self.pad = pad
        
        # backward用
        self.X_hat = None
        self.F_col = None
        
    def forward(self, X):
        self.X = X
        N, C, H, W = X.shape
        FN, C, FH, FW = self.F.shape
        self.stride = stride
        self.pad = pad
        
        # 出力サイズ
        OH = (H + 2*pad - FH) // stride + 1
        OW = (W + 2*pad - FW) // stride + 1
        
        # (N, C, H, W)のうちH, W方向にのみpadding
        X_pad = np.pad(X, [(0, 0), (0, 0), (pad, pad), (pad, pad)])
        
        # X_hat(空箱)を用意。型は(N, C, FH, FW, OH, OW)
        X_hat = np.zeros((N, C, FH, FW, OH, OW))
        
        for fh in range(FH):
            for fw in range(FW):
                X_hat[:, :, fh, fw, :, :] = X_pad[:, :, fh:fh+OH*stride:stride, fw:fw+OW*stirde:stride]
                
        # 引き伸ばしてベクトル内積計算に持ち込む
        # 目標のX_col.shape: (N, OH, OW, C*FH*FW)
        # まずは(N, OH, OW, C, FH, FW)にしたい
        # X_hat.shape: (N, C, FH, FW, OH, OW)
        X_tilde = X_hat.transpose(0, 4, 5, 1, 2, 3) # X_tilde.shape: (N, OH, OW, C, FH, FW)
        X_col = X_tilde.reshape(N, OH, OW, -1) # (N, OH, OW, C*FH*FW)
        
        # 出力yを計算
        F_col = self.F.reshape(FN, -1).T # F_col.shape: (FN, C*FH*FW) → (C*FH*FW, FN)
        # np.dot(X_col, F_col).shape: (N, OH, OW, FN)
        # y.shape: (N, FN, OH, OW)
        # transpose(0, 3, 1, 2)
        # b.shape: (FN,)
        y = (np.dot(X_col, F_col) + self.b).transpose(0, 3, 1, 2) # (N, FN, OH, OW)
        
        # backwardで使うから保存
        self.X_hat = X_hat
        self.F_col = F_col
        
        return y
    
    def backward(self, dy):
        N, FN, OH, OW = dy.shape
        FN, C, FH, FW = self.F.shape
        N, C, H, W = self.X.shape
        stride = self.stride
        pad = self.pad
        
        # dF, dbを算出
        # X_hat.shape: (N, C, FH, FW, OH, OW)
        # X_hat_col.shape: (C, FH, FW, -1)
        # とりあえずの目標shape: (C, FH, FW, N, OH, OW)
        X_hat_col = self.X_hat.transpose(1, 2, 3, 0, 4, 5).reshape(C, FH, FW, -1)
        # dy.shape: (N, FN, OH, OW)
        # dy_col.shapeは(FN, -1)にしたい
        # まずは(FN, N, OH, OW)にtranspose
        dy_col = dy.transpose(1, 0, 2, 3).reshape(FN, -1) # dy_col.shape: (FN, -1)
        self.db = dy_col.sum(axis=1) # db.shape: (FN,)
        # (FN, N*OH*OW)(C, FH, FW, N*OH*OW) → (FN, C, FH, FW)
        self.dF = np.dot(dy_col, X_hat_col.transpose(0, 1, 3, 2))
        
        # (N, OH, OW, FN)(C, FH, FN, FW) → (N, OH, OW, C, FH, FW)
        dX_tilde = np.dot(dy.transpose(0, 2, 3, 1), self.F.transpose(1, 2, 0, 3))
        
        # dX_tildeからdXを算出
        dX = np.zeros((N, C, H+2*pad+stride-1, W+2*pad+stride-1))
        for fh in range(FH):
            for fw in range(FW):
                dX[:, :, fh:fh+OH*stride:stride, fw:fw+OW*stride:stride] += dX_tilde[:, :, :, :, fh, fw]
                
        return dX[:, :, pad:H+pad, pad:W+pad]

### **【問題3】最大プーリング層の作成**

**まずは2次元配列の場合を考える**

In [21]:
class Pooling:
    def __init__(self, S):
        self.S = S
        
        # backward用
        self.argmax = None
        
    def forward(self, X):
        H, W = X.shape
        S = self.S
        FH, FW = S, S
        stride = S

        # 出力サイズ
        OH = H // S
        OW = W // S
        
        X_hat = np.zeros((FH, FW, OH, OW))
        for fh in range(FH):
            for fw in range(FW):
                X_hat[fh, fw, :, :] = X[fh:fh+OH*stride:stride, fw:fw+OW*stride:stride]
        X_tilde = X_hat.transpose(2, 3, 0, 1) # (OH, OW, FH, FW)
        X_col = X_tilde.reshape(OH, OW, -1) # (OH, OW, FH*FW)
        
        y = X_col.max(axis=2)
        return y

In [22]:
y = np.arange(16).reshape(4, 4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
pool = Pooling(2)
pool.forward(y)

array([[ 5.,  7.],
       [13., 15.]])

**N, Cを加えたものを考える**

In [24]:
class MaxPool2D:
    def __init__(self, S):
        self.S = S
        
        # backward用
        self.argmax = None
        
    def forward(self, X):
        N, C, H, W = X.shape
        S = self.S
        FH, FW = S, S
        stride = S

        # 出力サイズ
        OH = H // S
        OW = W // S
        
        X_hat = np.zeros((N, C, FH, FW, OH, OW))
        for fh in range(FH):
            for fw in range(FW):
                X_hat[:, :, fh, fw, :, :] = X[:, :, fh:fh+OH*stride:stride, fw:fw+OW*stride:stride]
        X_tilde = X_hat.transpose(0, 1, 4, 5, 2, 3) # (N, C, OH, OW, FH, FW)
        X_col = X_tilde.reshape(N, C, OH, OW, -1) # (N, C, OH, OW, FH*FW)
        
        y = X_col.max(axis=4) # (N, C, OH, OW)
        return y

In [25]:
# 4次元配列
x = np.array([[[[1, 2, 3, 4], [5, 6, 7, 8], [16, 15, 14, 13], [12, 11, 10, 9]],
              [[4, 3, 2, 1], [8, 7, 6, 5], [12, 11, 10, 9], [16, 15, 14, 13]]]])
x

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [16, 15, 14, 13],
         [12, 11, 10,  9]],

        [[ 4,  3,  2,  1],
         [ 8,  7,  6,  5],
         [12, 11, 10,  9],
         [16, 15, 14, 13]]]])

In [26]:
pool = MaxPool2D(2)
pool.forward(x)

array([[[[ 6.,  8.],
         [16., 14.]],

        [[ 8.,  6.],
         [16., 14.]]]])

**backwardも含めたPoolingクラスを考える**

逆伝搬における畳み込み層との最大の違いは，入力  X  を変形した配列である  X_tilde   とフィルターとの内積をとる代わりに，最大値をとっている点

$$ y = max([x_0, x_1, ..., x_{i-1}]) $$

を考える。どのx_iで最大値を取ったのかで状況は変わる。

$$ \frac{\partial y}{\partial x_i} = 1 (y = x_i), 0 (otherwise) $$

In [27]:
def dmax(x):
    dx = np.zeros_like(x)
    i = x.argmax()
    dx[i] = 1
    return dx

In [28]:
x = np.array([3, 3, 9, 7, 2, 1, 3, 5])
dmax(x)

array([0, 0, 1, 0, 0, 0, 0, 0])

In [29]:
def dmax2(x):
    I = x.shape[0]
    print('I:', I)
    y = x.max(axis=1)
    print('y:', y)
    arg = x.argmax(axis=1)
    print('arg:', arg)
    
    dy = y
    print('dy:', dy)
    dx = np.zeros_like(x)
    print('dx:', dx)
    dx[np.arange(I), arg] = dy
    return dx

In [30]:
x = np.array([[3, 5, 2, 12],
              [7, 9, 2, 3],
             [8, 2, 8, 4]])

dmax2(x)

I: 3
y: [12  9  8]
arg: [3 1 0]
dy: [12  9  8]
dx: [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


array([[ 0,  0,  0, 12],
       [ 0,  9,  0,  0],
       [ 8,  0,  0,  0]])

**backwardも含めたPoolingクラス完成版**

In [31]:
class MaxPool2D:
    def __init__(self, S):
        self.S = S
        
        # backward用
        self.argmax = None
        
    def forward(self, X):
        self.X = X
        N, C, H, W = X.shape
        S = self.S
        FH, FW = S, S
        stride = S

        # 出力サイズ
        OH = H // S
        OW = W // S
        
        X_hat = np.zeros((N, C, FH, FW, OH, OW))
        for fh in range(FH):
            for fw in range(FW):
                X_hat[:, :, fh, fw, :, :] = X[:, :, fh:fh+OH*stride:stride, fw:fw+OW*stride:stride]
        X_tilde = X_hat.transpose(0, 1, 4, 5, 2, 3) # (N, C, OH, OW, FH, FW)
        X_col = X_tilde.reshape(N, C, OH, OW, -1) # (N, C, OH, OW, FH*FW)
        
        y = X_col.max(axis=4) # (N, C, OH, OW)
        return y
    
    def backward(self, dy):
        N, C, H, W = self.X.shape
        N, C, OH, OW = dy.shape
        S = self.S
        FH, FW = S, S 
        stride = S
   
        # dy と　self.argmax から dX_tilde を計算
        dX_tilde = np.zeros((N*C*OH*OW, FH*FW))
        # (N*C*OH*OW, FH*FW) =  (N*C*OH*OW)
        dX_tilde[np.arange(N*C*OH*OW), self.argmax] = dy.flatten()
        dX_tilde = dX_tilde.reshape(N, C, OH, OW, FH, FW) 
        
        #  dX_tilde から dX を計算
        dX = np.zeros((N, C, H+stride-1, W+stride-1))  
        for fh in range(FH):
            for fw in range(FW):
                dx[:, :, fh:fh+OH*stride:stride, fw:fw+OW*stride:stride] += dX_tilde[:, :, :, :, fh, fw]
    
        return dx[:, :, :H, :W]

### **【問題4】（アドバンス課題）平均プーリングの作成**

**forwardのみ**

In [32]:
class AveragePooling:
    def __init__(self, S):
        self.S = S
        
    def forward(self, X):
        H, W = X.shape
        S = self.S
        FH, FW = S, S
        stride = S

        # 出力サイズ
        OH = H // S
        OW = W // S
        
        X_hat = np.zeros((FH, FW, OH, OW))
        for fh in range(FH):
            for fw in range(FW):
                X_hat[fh, fw, :, :] = X[fh:fh+OH*stride:stride, fw:fw+OW*stride:stride]
        X_tilde = X_hat.transpose(2, 3, 0, 1) # (OH, OW, FH, FW)
        X_col = X_tilde.reshape(OH, OW, -1) # (OH, OW, FH*FW)
        
        y = X_col.mean(axis=2)
        return y

In [33]:
a = np.arange(16).reshape(4, 4)

In [34]:
avepool = AveragePooling(2)
avepool.forward(a)

array([[ 2.5,  4.5],
       [10.5, 12.5]])

**backwardも込み**

In [35]:
class AveragePooling:
    def __init__(self, S):
        self.S = S
        
        # backward用
        self.argmax = None
        
    def forward(self, X):
        H, W = X.shape
        S = self.S
        FH, FW = S, S
        stride = S

        # 出力サイズ
        OH = H // S
        OW = W // S
        
        X_hat = np.zeros((FH, FW, OH, OW))
        for fh in range(FH):
            for fw in range(FW):
                X_hat[fh, fw, :, :] = X[fh:fh+OH*stride:stride, fw:fw+OW*stride:stride]
        X_tilde = X_hat.transpose(2, 3, 0, 1) # (OH, OW, FH, FW)
        X_col = X_tilde.reshape(OH, OW, -1) # (OH, OW, FH*FW)
        
        y = X_col.mean(axis=2)
        return y

### **【問題5】平滑化**

In [36]:
class Flatten:
    def __init__(self):
        pass
        
    def forward(self, X):
        self.X = X
        self.N, self.C, self.H, self.W = self.X.shape
        y = self.X.flatten()
        return y
    
    def backward(self, dy):
        self.dy = dy
        dX = self.dy.reshape(self.N, self.C, self.H, self.W)
        return dX

In [37]:
x = np.array([[[[1, 2, 3, 4], [5, 6, 7, 8], [16, 15, 14, 13], [12, 11, 10, 9]],
              [[4, 3, 2, 1], [8, 7, 6, 5], [12, 11, 10, 9], [16, 15, 14, 13]]]])

In [38]:
flatten = Flatten()
flatten.forward(x)

array([ 1,  2,  3,  4,  5,  6,  7,  8, 16, 15, 14, 13, 12, 11, 10,  9,  4,
        3,  2,  1,  8,  7,  6,  5, 12, 11, 10,  9, 16, 15, 14, 13])

In [39]:
dy = np.arange(32)
flatten.backward(dy)

array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31]]]])

### **【問題6】学習と推定**

In [40]:
from keras.datasets import mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()

Using TensorFlow backend.


In [41]:
print('X_train.shape:', X_train.shape)
print('y_train.shape:', y_train.shape)
print('X_test.shape:', X_test.shape)
print('y_test.shape:', y_test.shape)

X_train.shape: (60000, 28, 28)
y_train.shape: (60000,)
X_test.shape: (10000, 28, 28)
y_test.shape: (10000,)


In [42]:
X_train[0].reshape(1, 28, 28).shape

(1, 28, 28)

In [43]:
X_train.reshape(X_train.shape[0], 1, 28, 28).shape

(60000, 1, 28, 28)

In [44]:
X_train = X_train.reshape(X_train.shape[0], 1, 28, 28)
X_test = X_test.reshape(X_test.shape[0], 1, 28, 28)

In [45]:
print('X_train.shape:', X_train.shape)
print('X_test.shape:', X_test.shape)

X_train.shape: (60000, 1, 28, 28)
X_test.shape: (10000, 1, 28, 28)


In [100]:
class SGD:
    def __init__(self, lr=0.01):
        self.lr = lr
        
    def update(self, params, grads):
        for key in params:
            params[key] -= self.lr * grads[key]
            
class AdaGrad:
    def __init__(self, lr=0.01):
        self.lr = lr
        self.h = None
        
    def update(self, params, grads):
        if self.h is None:
            self.h = {}
            for key in params:
                self.h[key] = np.zeros_like(params[key])
                
        for key in params:
            self.h[key] += grads[key] * grads[key]
            params[key] -= self.lr * grads[key] / (np.sqrt(self.h[key]) + 1e-7)

In [106]:
def softmax(a):   
    # a がベクトルのとき
    if a.ndim == 1:
        c = np.max(a)#オーバーフロー対策1
        x = a-c
        x = 709*(x >= 709) + x*(x<709)#オーバーフロー対策2
        exp_x = np.exp(x)
        sum_exp_x = np.sum(exp_x)
        return exp_x/sum_exp_x
    
    # a が２階の配列のとき
    a = a.T
    c = np.max(a, axis=0) #オーバーフロー対策1
    x = a - c
    x = 709*(x >= 709) + x*(x<709) #オーバーフロー対策2
    exp_x = np.exp(x)
    sum_exp_x = np.sum(exp_x, axis=0)
    return (exp_x/sum_exp_x).T

def sigmoid(x):
    x = -709*(x <= -709)+709*(x >= 709) + x*(x>-709) *(x<709) #オーバーフロー対策
    return 1/(1+np.exp(-x))

class Affine:
    def __init__(self, W, b):
        self.W = W
        self.b = b
        self.X = None
        self.dW = None
        self.db = None
        self.Xshape = None
        
    def forward(self, X):
        self.Xshape = X.shape
        X = X.reshape(self.Xshape[0], -1)
        
        self.X = X
        A = np.dot(self.X, self.W) + self.b
        return A
    
    def backward(self, dZ):
        self.dW = np.dot(self.X.T, dZ)
        self.db = np.sum(dZ, axis=0)
        dX = np.dot(dZ, self.W.T)
        
        dX = dX.reshape(*self.Xshape)
        return dX
    
class Relu:
    def __init__(self):
        self.mask = None
        
    def forward(self, X):
        self.mask = (X > 0)
        y = X * self.mask
        return y
    
    def backward(self, dy):
        dX = dy * self.mask
        return dX
    
class Sigmoid:
    def __init__(self):
        sely.y = None
        
    def forward(self, X):
        self.y = sigmoid(X)
        return self.y
    
    def backward(self, dy):
        dX = dy * (1 - self.y) * self.y
        return dX
    
class SoftmaxWithLoss:
    def __init__(self):
        self.loss = None
        self.y = None
        self.t = None
        
    def forward(self, X, t):
        y = softmax(X)
        self.y = y
        self.t = t
        batch_size = y.shape[0]
        return -np.sum(t * np.log(y + 1e-7)) / batch_size
    
    def backward(self):
        batch_size = self.y.shape[0]
        dX = (self.y - self.t) / batch_size
        return dX
    
class Convolution:
    def __init__(self, F, b, stride=1, pad=0):
        self.F = F
        self.b = b
        self.stride = stride
        self.pad = pad
        
        self.Xshape = None
        self.X_hat = None
        self.f_col = None
        
        self.dF = None
        self.db = None
        
    def forward(self, X):
        self.Xshape = X.shape
        FN, C, FH, FW = self.F.shape
        N, C, H, W = self.Xshape
        pad = self.pad
        stride = self.stride
        
        OH = (H + 2*pad - FH) // stride + 1
        OW = (W + 2*pad - FW) // stride + 1
        
        X_pad = np.pad(X, [(0, 0), (0, 0), (pad, pad), (pad, pad)])
        X_hat = np.zeros((N, C, FH, FW, OH, OW))
        for fh in range(FH):
            for fw in range(FW):
                X_hat[:, :, fh, fw, :, :] = X_pad[:, :, fh:fh+OH*stride:stride, fw:fw+OW*stride:stride]
        X_tilde = X_hat.transpose(0, 4, 5, 1, 2, 3)
        X_col = X_tilde.reshape(N, OH, OW, -1)
        
        f_col = self.F.reshape(FN, -1).T
        y = (np.dot(X_col, f_col) + self.b).transpose(0, 3, 1, 2)
        
        self.X_hat = X_hat
        self.f_col = f_col

        return y
    
    def backward(self, dy):
        FN, C, FH, FW = self.F.shape
        N, FN, OH, OW = dy.shape
        N, C, H, W = self.Xshape
        stride = self.stride
        pad = self.pad
        
        X_hat_col = self.X_hat.transpose(1, 2, 3, 0, 4, 5).reshape(C, FH, FW, -1)
        dy_col = dy.transpose(1, 0, 2, 3).reshape(FN, -1)
        self.db = dy_col.sum(axis=1)
        self.dF = np.dot(dy_col, X_hat_col.transpose(0, 1, 3, 2))
        
        dX_tilde = np.dot(dy.transpose(0, 2, 3, 1), self.F.transpose(1, 2, 0, 3))
        dX_tilde = dX_tilde.transpose(0, 3, 1, 2, 4, 5)
        
        dX = np.zeros((N, C, H+2*pad+stride-1, W+2*pad+stride-1), dtype=np.float)
        for fh in range(FH):
            for fw in range(FW):
                dX[:, :, fh:fh+OH*stride:stride, fw:fw+OW*stride:stride] += dX_tilde[:, :, :, :, fh, fw]
        return dX[:, :, pad:H+pad, pad:W+pad]
    
class MaxPool2D:
    def __init__(self, S):
        self.S = S
        
        # backward用
        self.Xshape = None
        self.argmax = None
        
    def forward(self, X):
        self.Xshape = X.shape
        N, C, H, W = X.shape
        S = self.S
        FH, FW = S, S
        stride = S

        # 出力サイズ
        OH = H // S
        OW = W // S
        
        X_hat = np.zeros((N, C, FH, FW, OH, OW))
        for fh in range(FH):
            for fw in range(FW):
                X_hat[:, :, fh, fw, :, :] = X[:, :, fh:fh+OH*stride:stride, fw:fw+OW*stride:stride]
        X_tilde = X_hat.transpose(0, 1, 4, 5, 2, 3) # (N, C, OH, OW, FH, FW)
        X_col = X_tilde.reshape(N, C, OH, OW, -1) # (N, C, OH, OW, FH*FW)
        
        self.argmax = X_col.argmax(axis=-1).flatten()
        
        y = X_col.max(axis=4) # (N, C, OH, OW)
        return y
    
    def backward(self, dy):
        N, C, H, W = self.Xshape
        N, C, OH, OW = dy.shape
        S = self.S
        FH, FW = S, S 
        stride = S
   
        # dy と　self.argmax から dX_tilde を計算
        dX_tilde = np.zeros((N*C*OH*OW, FH*FW))
        # (N*C*OH*OW, FH*FW) =  (N*C*OH*OW)
        dX_tilde[np.arange(N*C*OH*OW), self.argmax] = dy.flatten()
        dX_tilde = dX_tilde.reshape(N, C, OH, OW, FH, FW) 
        
        #  dX_tilde から dX を計算
        dX = np.zeros((N, C, H+stride-1, W+stride-1))  
        for fh in range(FH):
            for fw in range(FW):
                dx[:, :, fh:fh+OH*stride:stride, fw:fw+OW*stride:stride] += dX_tilde[:, :, :, :, fh, fw]
    
        return dx[:, :, :H, :W]

In [115]:
from collections import OrderedDict

class CNN:
    def __init__(self, input_dim=(1, 28, 28), optimizer=AdaGrad):
        self.all_dim_list = [input_dim]
        self.params = {}
        self.optimizer = optimizer()
        self.layers = OrderedDict()
        self.lastLayer = SoftmaxWithLoss()
        self.idx = 0
        
    def affine(self, size, activation='relu'):
        self.idx += 1
        idx = self.idx
        self.all_dim_list.append(size)
        
        # Heの初期化
        sigma = np.sqrt(2 / np.prod(self.all_dim_list[idx - 1]))
        self.params['W' + str(idx)] = sigma * np.random.randn(np.prod(self.all_dim_list[idx - 1]), size)
        self.params['b' + str(idx)] = np.zeros(size)
        
        # Affine層の追加
        self.layers['Affine' + str(idx)] = Affine(self.params['W' + str(idx)], self.params['b' + str(idx)])
        
        if activation == 'relu':
            self.layers['Relu' + str(idx)] = Relu()
        if activation == 'sigmoid':
            self.layers['Sigmoid' + str(idx)] = Sigmoid()
            
    def convolution(self, FN, FH, FW, stride=1, pad=0, S=1, activation=None):
        self.idx += 1
        idx = self.idx
        C, H, W = self.all_dim_list[idx - 1]
        
        OH = (H + 2*pad - FH) // stride + 1
        OW = (W + 2*pad - FW) // stride + 1
        
        sigma = np.sqrt((2 / (C*FH*FW)))
        self.params['F' + str(idx)] = sigma * np.random.randn(FN, C, FH, FW)
        self.params['b' + str(idx)] = sigma * np.random.randn(FN)
        
        self.layers['Conv' + str(idx)] = Convolution(self.params['F' + str(idx)], self.params['b' + str(idx)], stride=stride, pad=pad)
        
        # 活性化層の追加
        if activation == 'relu':
            self.layers['Relu' + str(idx)] = Relu()
        if activation == 'sigmoid':
            self.layers['Sigmoid' + str(idx)] = Sigmoid()
        
        if S > 1:
            self.layers['Pooling' + str(idx)] = MaxPool2D(S)
            OH = OH // S
            OW = OW // S
        
        self.all_dim_list.append((FN, OH, OW))
        
    def predict(self, X):
        for key, layer in self.layers.items():
            X = layer.forward(X)
        return X
    
    def loss(self, X, t):
        y = self.predict(X)
        print('y.shape:', y.shape)
        print('t.shape:', t.shape)
        return self.lastLayer.forward(X, t)
    
    def accuracy(self, X, t, batch_size=100):
        acc = 0
        for i in range(int(X.shape[0] / batch_size)):
            tx = X[i*batch_size:(i+1)*batch_size]
            tt = t[i*batch_size:(i+1)*batch_size]
            #print('tt.shape:', tt.shape)
            y = self.predict(tx)
            y = np.argmax(y, axis=1)
            tt = np.argmax(tt)
            acc += np.sum(y == tt)   
        return acc / X.shape[0]
    
    def gradient(self, X, t):
        self.loss(X, t)
        dy = self.lastLayer.backward()
        
        layers = list(self.layers.values())
        layers.reverse()
        for layer in layers:
            dy = layer.backward(dy)
            
        grads = {}
        all_num = len(self.all_dim_slist)
        
        for idx in range(1, all_num):
            if type(self.all_dim_list[idx]) == int:
                grads['W' + str(idx)] = self.layers['Affine' + str(idx)].dW + self.params['W' + str(idx)]
                grads['b' + str(idx)] = self.layers['Affine' + str(idx)].db
            else:
                grads['F' + str(idx)] = self.layers['Conv' + str(idx)].dF + self.params['F' + str(idx)]
                grads['b' + str(idx)] = self.layers['Conv' + str(idx)].fb

        return grads
    
    def fit(self, X_train, y_train, X_test, y_test, iters_num=1000, batch_size=100):
        self.train_accuracy_list = []
        optimizer = self.optimizer
        train_size = X_train.shape[0]
        
        for i in range(iters_num):
            if i%int(iters_num/20) == 0:
                accuracy = self.accuracy(X_test, y_test)
                self.train_accuracy_list.append(accuracy)
                print('iteration =', i, ', accuracy = ', accuracy)
                
            batch_mask = np.random.choice(train_size, batch_size, replace=False)
            X_batch = X_train[batch_mask]
            t_batch = y_train[batch_mask]
            print('X_batch:', X_batch.shape)
            
            grads = self.gradient(X_batch, t_batch)
            optimizer.update(self.params, grads)
            
        accuracy = self.accuracy(X_test, t_test)
        self.train_accuracy_list.append(accuracy)
        print('iteration = ', iters_num, ', accuracy = ', accuracy)

In [116]:
network = CNN(input_dim=(1, 28, 28), optimizer=AdaGrad)
network.convolution(FN=30, FH=5, FW=5, S=2, activation='relu')
network.affine(100)
network.affine(10, activation=None)

In [117]:
print(network.all_dim_list)
network.layers

[(1, 28, 28), (30, 12, 12), 100, 10]


OrderedDict([('Conv1', <__main__.Convolution at 0xb41db1fd0>),
             ('Relu1', <__main__.Relu at 0xb41db1b38>),
             ('Pooling1', <__main__.MaxPool2D at 0xb41db1f60>),
             ('Affine2', <__main__.Affine at 0xb41db1080>),
             ('Relu2', <__main__.Relu at 0x121f39198>),
             ('Affine3', <__main__.Affine at 0x121f39b70>)])

In [118]:
network.fit(X_train, y_train, X_test, y_test, iters_num=1000, batch_size=100)
X = np.arange(0, len(network.train_accuracy_list), 1)
plt.plot(X, network.train_accuracy_list, label='AdaGrad')

plt.legend();

iteration = 0 , accuracy =  0.0697
X_batch: (100, 1, 28, 28)
y.shape: (100, 10)
t.shape: (100,)


ValueError: operands could not be broadcast together with shapes (100,) (100,1,28,28) 