## 行列積のスクラッチ

### 【問題1】行列積を手計算する

In [1]:
import numpy as np

In [2]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

Aのi行目(i=1, 2, 3)をベクトル（ベクトルiとする）と見做し、Bのj列目(j=1, 2, 3)もベクトル（ベクトルjとする）と見做す。AとBの行列積ABの(i, j)成分はベクトルiとベクトルjの内積によって得られる。
例）ABの(1, 1)成分AB(1, 1)の計算
　AB(1, 1) = (-1)×0 + 2×0 + 3×2 = 6
 
全てのについて同様の計算を行うとABは以下になる。

AB = [[6, 29, -20],
      [12, 52, 38],
      [-18, -51, -48]]

### 【問題2】Numpyの関数による計算

In [3]:
# np.matmul()の利用

a_b0 = np.matmul(a_ndarray, b_ndarray)
print(a_b0)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [4]:
# np.dot()の利用

a_b1 = np.dot(a_ndarray, b_ndarray)
print(a_b1)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [5]:
# 演算子@の利用

a_b2 = a_ndarray @ b_ndarray
print(a_b2)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


### 【問題3】ある要素の計算を実装

In [6]:
default_array0 = np.zeros((a_ndarray.shape[0], b_ndarray.shape[1]))

for i in range(a_ndarray.shape[0]):
    for j in range(b_ndarray.shape[1]):
        for k in range(a_ndarray.shape[1]):
            default_array0[i, j] += a_ndarray[i, k] * b_ndarray[k, j]
print(default_array0)

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


### 【問題4】行列積を行う関数の作成

In [7]:
def matrix_mul(matrix1, matrix2):
    default_array = np.zeros((matrix1.shape[0], matrix2.shape[1]))
    
    for i in range(matrix1.shape[0]):
        for j in range(matrix2.shape[1]):
            for k in range(matrix1.shape[1]):
                default_array[i, j] = matrix1[i, k] * matrix2[k, j]
                
    return default_array
  
print(matrix_mul(a_ndarray, b_ndarray))

[[  6.  27.  -3.]
 [ 12.  54.  -6.]
 [-18. -81.   9.]]


### 【問題5】計算が定義されていない入力を判定する

In [8]:
def modified_matrix_mul(matrix1, matrix2):
    if matrix1.shape[1] == matrix2.shape[0]:
        ndarray = np.zeros((matrix1.shape[0], matrix2.shape[1]))
        
        for i in range(matrix1.shape[0]):
            for j in range(matrix2.shape[1]):
                for k in range(matrix1.shape[1]):
                    ndarray[i, j] += matrix1[i, k] * matrix2[k, j]
                    
        return ndarray
      
    else:
        error_message = 'matrix1の列数とmatrix2の行数が異なるため、計算できません。'
        
        return error_message

In [9]:
print(modified_matrix_mul(a_ndarray, b_ndarray))

c_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
d_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
print(modified_matrix_mul(c_ndarray, d_ndarray))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]
matrix1の列数とmatrix2の行数が異なるため、計算できません。


### 【問題6】転置

In [10]:
result = []
for i in range(3):
    for j in range(3):
        result.append(sum(a_ndarray[i] * b_ndarray.T[j]))
result_array = np.array(result)
result_array_ab = result_array.reshape(3, 3)
print(result_array_ab)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [11]:
# 関数にしてみる

def get_matrix_mul(matrix1, matrix2):
    fai_list = []
    for i in range(matrix1.shape[0]):
        for j in range(matrix2.shape[1]):
            fai_list.append(sum(matrix1[i] * matrix2.T[j]))
    mul_array = np.array(fai_list)
    mul_ndarray = mul_array.reshape(matrix1.shape[0], matrix2.shape[1])
    
    return mul_ndarray

In [12]:
print(get_matrix_mul(a_ndarray, b_ndarray))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
